export default async function getFailure() {
  throw new Error('user error')
}
